CC=gcc
CFLAGS=-I. -g -O0 -Wall -pedantic `pkg-config --cflags gstreamer-1.0` `sdl2-config --cflags`

LIBS=-lm -lGLU -lpng `pkg-config --libs gstreamer-1.0` `pkg-config --libs gstreamer-app-1.0` `sdl2-config --libs`

%.o: %.c *.h
	$(CC) -c -o $@ $< $(CFLAGS)

BeautyDrive: sys_sdl2.o vid_sdl2.o dec_gst.o in_sdl.o physics_minimal.o renderer.o game.o key.o map.o vector.o
	$(CC) -o $@ $^ $(CFLAGS) $(LIBS)

.PHONY: clean

clean:
	rm -f *.o core
